### ISSUE TITLE
Japanese character is garbled

### ISSUE THREAD

**Issue by wakanasato** [Esri/arcgis-runtime-samples-android#222] opened 2016-09-15 06:42 UTC
Japanese character is garbled when I call any Layer by REST from AGOL.
The registed data in AGOL is point data layer which is English and Japanese of attributes.
The data displaies on the map is no error.
However, when I create FeatureTable object and to execution of a query for FeatureTable object and get the result,this result is unreadable in Japanese.

for example:
Title = ?????

You can see the true result of execute query at next REST URL. 
http://services.arcgis.com/wlVTGRSYTzAbjjiC/arcgis/rest/services/testPoint/FeatureServer/1/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=%22*%22&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=html&token=

Please use my data:AGOL public data.
http://www.arcgis.com/home/item.html?id=418ab72b1f824497bf1a996811ff09d4#data
Tried REST URL(point Layer)
# use point layer data! Choose second data in the layer choose  dropdown.

Sample code for execution of a query:see next. 
https://github.com/Esri/arcgis-runtime-samples-android/tree/quartz-beta/feature-layer-query

**Comment by doneill** [comment] 2016-10-27 19:57
@wakanasato While I have been unable to reproduce the issue with your data we are aware of the issue and have verified a fix which will be released with Quartz v100.0.0 SDK final.

**Comment by doneill** [comment] 2016-12-01 18:23
@wakanasato Can you verify the fix in the released [sample](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/feature-layer-query)?

**Comment by wakanasato** [comment] 2016-12-15 08:13
I confirmed this [sample](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/feature-layer-query) that Japanese will be processed correctly. The [data](http://www.arcgis.com/home/item.html?id=418ab72b1f824497bf1a996811ff09d4#data) I presented also worked correctly. Very helpful. Thanks!

**Comment by doneill** [comment] 2016-12-20 00:55
@wakanasato Thanks for verifying!

**Closed by doneill** 2016-12-20 00:55 UTC
Labels: 3 - ToVerify, A - Bug-SDK, B - High
