### ISSUE TITLE
OfflineAnalysis sample does not work

### ISSUE THREAD

**Issue by ddurgaprasad** [Esri/arcgis-runtime-samples-android#203] opened 2016-07-16 01:31 UTC
Both LOS and Viewshed failed to run when using OfflineAnalysis sample with a sample Geotiff.The app closes with the error '_Unfortunately,OfflineAnalysis has stopped_'.

I am getting same result irrespective of the type of device or size of Geotiff.I get same error on multiple devices-Motog3 , Samsung S6 ,Nexus9 tab

**Comment by doneill** [comment] 2016-07-16 04:29
@ddurgaprasad Did you add the Analysis Beta Libs?  And confirmed you are able to get to the path correctly on device?  If so, please share more from the logcat and any steps you did to set this up.

**Comment by ddurgaprasad** [comment] 2016-07-16 09:01
@doneill Followed work instructions and copied libs to below path 
OfflineAnalysis\src\main\jniLibs\libs
   armeabi\librender_script_analysis.so
                \librs.main.so
                 \libruntimecore_java.so
 armeabi-v7a\librender_script_analysis.so
                \librs.main.so
                 \libruntimecore_java.so  
  x86\librender_script_analysis.so
                \librs.main.so
                 \libruntimecore_java.so
   arcgis-android-api
   arcgis-android-app-toolkit
   jackson-core-1.9.5
   jackson-mapper-1.9.5
   jcifs-1.3.17

As described in sample,I have copied the Geotiff to this location...via USB connection from laptop.
Computer\Galaxy S6\Phone\ArcGIS\samples\OfflineAnalysis

**Logcat output:**
07-16 14:28:17.761 9387-9387/? E/Zygote: MountEmulatedStorage()
07-16 14:28:17.761 9387-9387/? E/Zygote: v2
07-16 14:28:17.761 9387-9387/? I/libpersona: KNOX_SDCARD checking this for 10283
07-16 14:28:17.761 9387-9387/? I/libpersona: KNOX_SDCARD not a persona
07-16 14:28:17.761 9387-9387/? I/SELinux: Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_SM-G920I_5.1.1 ver=51
07-16 14:28:17.761 9387-9387/? I/SELinux: Function: selinux_compare_spd_ram , priority [1] , priority version is VE=SEPF_SM-G920I_5.1.1_0051
07-16 14:28:17.761 9387-9387/? E/Zygote: accessInfo : 0
07-16 14:28:17.761 9387-9387/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
07-16 14:28:17.761 9387-9387/? I/art: Late-enabling -Xcheck:jni
07-16 14:28:17.771 9387-9387/? D/TimaKeyStoreProvider: TimaSignature is unavailable
07-16 14:28:17.771 9387-9387/? D/ActivityThread: Added TimaKeyStore provider
07-16 14:28:17.811 9387-9387/com.esri.arcgis.samples.offlineanalysis I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
07-16 14:28:17.831 9387-9387/com.esri.arcgis.samples.offlineanalysis I/InjectionManager: Inside getClassLibPath caller 
07-16 14:28:17.831 9387-9387/com.esri.arcgis.samples.offlineanalysis D/InjectionManager: InjectionManager
07-16 14:28:17.831 9387-9387/com.esri.arcgis.samples.offlineanalysis D/InjectionManager: fillFeatureStoreMap com.esri.arcgis.samples.offlineanalysis
07-16 14:28:17.841 9387-9387/com.esri.arcgis.samples.offlineanalysis I/InjectionManager: Constructor com.esri.arcgis.samples.offlineanalysis, Feature store :{}
07-16 14:28:17.841 9387-9387/com.esri.arcgis.samples.offlineanalysis I/InjectionManager: featureStore :{}
07-16 14:28:17.861 9387-9387/com.esri.arcgis.samples.offlineanalysis D/SecWifiDisplayUtil: Metadata value : SecSettings2
07-16 14:28:17.921 9387-9387/com.esri.arcgis.samples.offlineanalysis D/PhoneWindow: *FMB* installDecor mIsFloating : false
07-16 14:28:17.921 9387-9387/com.esri.arcgis.samples.offlineanalysis D/PhoneWindow: *FMB* installDecor flags : 8454400
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis D/AndroidRuntime: Shutting down VM
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime: FATAL EXCEPTION: main
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime: Process: com.esri.arcgis.samples.offlineanalysis, PID: 9387
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.esri.arcgis.samples.offlineanalysis/com.esri.arcgis.samples.offlineanalysis.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.esri.android.map.MapView
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3125)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.access$1000(ActivityThread.java:198)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6843)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:  Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class com.esri.android.map.MapView
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:640)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2321)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.arcgis.samples.offlineanalysis.MainActivity.onCreate(MainActivity.java:86)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6500)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6843) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:614)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2321) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.arcgis.samples.offlineanalysis.MainActivity.onCreate(MainActivity.java:86) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6500) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6843) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:  Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.esri.arcgis.samples.offlineanalysis-1/base.apk"],nativeLibraryDirectories=[/data/app/com.esri.arcgis.samples.offlineanalysis-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libruntimecore_java.so"
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:988)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.core.internal.RuntimeHelper.a(SourceFile:85)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.core.internal.RuntimeHelper.initialize(SourceFile:47)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.android.map.MapSurface.<clinit>(SourceFile:68)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.android.map.MapView.a(SourceFile:586)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.android.map.MapView.<init>(SourceFile:621)
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Activity.setContentView(Activity.java:2321) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.esri.arcgis.samples.offlineanalysis.MainActivity.onCreate(MainActivity.java:86) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6500) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6843) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
07-16 14:28:30.211 9387-9387/com.esri.arcgis.samples.offlineanalysis I/Process: Sending signal. PID: 9387 SIG: 9

**Comment by doneill** [comment] 2016-07-17 20:02
@ddurgaprasad Your issue comes from this in your log output

```
07-16 14:28:17.941 9387-9387/com.esri.arcgis.samples.offlineanalysis E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.esri.arcgis.samples.offlineanalysis/com.esri.arcgis.samples.offlineanalysis.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.esri.android.map.MapView
```

The issue as stated is that the `MapView` class is not found. Looks like you are using all the libs from the local download.  Can you use the AAR dependency and remove all the other libs that are not required by the Analysis API?

Remove everything except:  

```
[platform]\librender_script_analysis.so
[platform]\librs.main.so
```

And add to your gradle build script(s):
```groovy
    repositories {
        maven {
            url 'https://esri.bintray.com/arcgis'
        }
    }
    dependencies {
        compile 'com.esri.arcgis.android:arcgis-android:10.2.8-1'
    }
```

This will help us determine where you are pulling the dependencies from and what platform you are using.

**Comment by doneill** [comment] 2016-10-27 19:58
Closing, @ddurgaprasad please follow up if you continue to see the issue after updating your build as mentioned above.

**Closed by doneill** 2016-10-27 19:58 UTC
Labels: A - Question

**Comment by parcool** [comment] 2016-11-29 10:55
i got the same issues,when i use it in fragment and be load by `LayoutInflater` and it crashed!samsung galaxy s7 edge 6.0.1
