### ISSUE TITLE
com.esri.arcgisruntime.sample.displaydevicelocation.R unable to locate please share. Tks

### ISSUE THREAD

**Issue by Sansun** [Esri/arcgis-runtime-samples-android#387] opened 2017-09-23 18:08 UTC
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Runtime SDK Samples. Use [GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android) for any general ArcGIS Runtime Android SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Sansun** [comment] 2017-09-23 18:10
The import com.esri.arcgisruntime.sample.displaydevicelocation.R is not to be found and so issues some variables getting resolved. 

Appreciate that the com.esri.arcgisruntime.sample.displaydevicelocation.R file be shared to resolve the issue.

Thank yoy
SVisuva

**Comment by TADraeseke** [comment] 2017-09-25 09:38
Hi Sansun,

Often issues with R not being resolved can be fixed by cleaning/rebuilding the project.

The way the samples are setup, they should run without any alteration to the code and I've just tested display-device-location and it seems to be running fine for me.

If re-cloning and cleaning the project don't help, could you explain how to reproduce your problem?

Kind regards,
Trevor

**Comment by Sansun** [comment] 2017-09-27 13:33
Hey Trevor,
Thank you so much for the reply. 
I am new to eSri ArgGis Runtime Android. And I started with the API version 100.1.0; 
I followed the instructions and able to build my first display-map app on Android with no issue and I can run the app on my Samsung Galaxy Tab 2 7" device using the USB debug fine, no issue. 

This is my second example based on the display-device-location. I only have this 3 files
`com.esri.arcgisruntime.sample.displaydevicelocation.MainActivity.java
 com.esri.arcgisruntime.sample.spinner.ItemData.java
 com.esri.arcgisruntime.sample.spinner.SpinnerAdapter.java

The MainActivity.java has these line of code which is not getting resolved:
    // Populate the list for the Location display options for the spinner's Adapter
    ArrayList<ItemData> list = new ArrayList<>();
    list.add(new ItemData("Stop", **R.drawable.locationdisplaydisabled**));
    list.add(new ItemData("On", **R.drawable.locationdisplayon**));
    list.add(new ItemData("Re-Center", **R.drawable.locationdisplayrecenter**));
    list.add(new ItemData("Navigation", **R.drawable.locationdisplaynavigation**));
    list.add(new ItemData("Compass", **R.drawable.locationdisplayheading**));
`
I used the build.gradle script to download the resources from maven{ url: 'https://esri.bintray.com/arcgis' } as in the instructions. Not sure it get all the required files to build the project. 

Appreciate any help.

Thank you

**Comment by Sansun** [comment] 2017-09-27 18:58
Update: Thank you Trevor, your comments helped me and I followed the complete installation of the eSri ArcGis Runtime SDK for Android Samples (Instructions here: https://github.com/Esri/arcgis-runtime-samples-android/wiki/dev-instructions) and its perfect now. No issues. 

Thank you again!

**Comment by TADraeseke** [comment] 2017-09-28 09:00
Brilliant! Enjoy the ArcGIS Runtime SDK :)

**Closed** 2017-09-28 09:00 UTC
